[package]
name = "motor-controller-v1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-serial = "5.4.1"
tokio = { version = "1.0", features = ["full"] }
tokio-modbus = { version = "*", default-features = false, features = ["rtu"] }